<div class="category-products">
<?php 
$items = $this->getItems();
$_helper = $this->helper('catalog/output');
if($items->getSize()):
?>
<div class="toolbar">
    <span class="label">
    <?= $this->__('Sort :'); ?>
    </span>
    <div class="actions" style="margin-bottom: 10px;">
        <?php if($this->showDescBtn()){ ?>
        <a href="<?= Mage::getUrl('list/index',array('sort'=>'asc')) ?>" class="button action action-sort asc">Acs</a>
        <?php }else{ ?>
        <a href="<?= Mage::getUrl('list/index',array('sort'=>'desc')) ?>" class="button action action-sort desc">Desc</a>
        <?php } ?>
    </div>
</div>
<ul class="products-grid">
<?php foreach ($items as $key => $item):
    //echo "<pre/>";print_r($item->getData());exit; ?>
<li class="item">
    <a href="<?php echo $item->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($item, 'small_image'), null, true) ?>" class="product-image">
        <?php $_imgSize = 210; ?>
        <img id="product-collection-image-<?php echo $item->getId(); ?>"
                src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize($_imgSize); ?>"
                alt="<?php echo $this->stripTags($this->getImageLabel($item, 'small_image'), null, true) ?>" />
    </a>
    <div class="product-info">
        <h2 class="product-name"><a href="<?php echo $item->getProductUrl() ?>" title="<?php echo $this->stripTags($item->getName(), null, true) ?>"><?php echo $item->getName() ?></a></h2>
        <?php
        // Provides extra blocks on which to hang some features for products in the list
        // Features providing UI elements targeting this block will display directly below the product name
        if ($this->getChild('name.after')) {
            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                $_nameAfterChild->setProduct($item);
                echo $_nameAfterChild->toHtml();
            }
        }
        ?>
        <?php 
            $productBlock = $this->getLayout()->createBlock('catalog/product_price');
            echo $productBlock->getPriceHtml($item, true);
        ?>
        <?php if($item->getRatingSummary()): ?>
        <?php echo $this->getReviewsSummaryHtml($item, 'short') ?>
        <?php endif; ?>
        <?php echo "Sort Order : ".$item->getSortOrder(); ?>
        <div class="actions">
            <?php if(!$item->canConfigure() && $item->isSaleable()): ?>
                <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
            <?php elseif($item->getStockItem() && $item->getStockItem()->getIsInStock()): ?>
                <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $item->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
            <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
            <ul class="add-to-links">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                <?php endif; ?>
                <?php if($_compareUrl=$this->getAddToCompareUrl($item)): ?>
                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</li>
<?php endforeach; ?>
</ul>
<?php endif; ?>
<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>

